# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6dfc7f275dca01a3014af7c1cc493c625e29626aea3f921b38bb53c1e8cfc8070dd19736e00f14775122a022467fb108fc3d98708d1646888d933d8dee143b9d

test:
  secret_key_base: 988897309e64aaf1f1711eb44ff85c64b8a716c9b731ae4ddc92a0eda9a11c937f7c0bc884ddff5e2cda5b35ec1359238c8f3a34dcaafb0134f447720f24b0b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
